# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20170923_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinformation',
            name='id',
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='user_id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
