# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20170923_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
