# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 12:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_userinformation_last_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInformation',
        ),
    ]
