# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 18:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20170923_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='action_photo_username',
        ),
        migrations.RemoveField(
            model_name='action',
            name='action_user_username',
        ),
        migrations.RemoveField(
            model_name='board',
            name='board_user_username',
        ),
        migrations.DeleteModel(
            name='Action',
        ),
        migrations.DeleteModel(
            name='board',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
